global:
  scrape_interval: 60s
  scrape_timeout: 60s


rule_files:
  # - "first.rules"
  # - "second.rules"
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ethexporter'
    static_configs:
      - targets: ['exporter:9306']
